name: Fuzz CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # checkout repository
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the target image
      id: push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/SpyrosSdougkas/miniwebradio:latest

    - name: Create a directory for storing test cases
      run: mkdir -p ${{ github.workspace }}/miniwebradio-testcases

    - name: Run fuzzing campaign
      run: timeout 300 docker run --rm -v ${{ github.workspace }}/miniwebradio-testcases:/output ghcr.io/SpyrosSdougkas/miniwebradio:latest /fuzz /output || true 

    - name: Change permissions for output folder
      run: sudo chown -R $USER ${{ github.workspace }}/miniwebradio-testcases

    - name: Compress test cases
      run: tar -czf ${{ github.workspace }}/miniwebradio-testcases.tar.gz -C ${{ github.workspace }} miniwebradio-testcases

    - name: Upload test cases as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: exim-testcases.tar.gz
        path: ${{ github.workspace }}/miniwebradio-testcases.tar.gz
